apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
    - name: busybox
      iamge: gcr.io/google_containers/busybox
      command:
        - sleep
        - "3600"
