apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: default
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    kind: Deploument
    name: php-apache
  targetCPUUilizationPercentage: 90
# 老版本需要heapster，新版本自动孵化了基础性能数据采集框架：Kuberneters Monitoring Architecture，定义了Resource Metrics API