apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    tier: frontend
  templete:
    metadata:
      labels:
        app: app-demo
        tier: frontend
    spec:
      containers:
        - name: tomcat-demo
          images: tomcat
          imagePullPolicy: IfNotPresent
          env:
            - name: GET_HOST_FROM
              value: dns
          ports:
            - containerPort: 80